In [4]:
import numpy as np

a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [5]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [10]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)

print(a.shape)
print(b.shape)

for i in range(3):
  for j in range(4):
    d[i][j] = a[i][j] + b[j]

print(d)

e = a + b.T
print(e)

(3, 4)
(4, 1)
[[-3.85551279  0.51310473 -1.3713166   1.30221375]
 [-3.44916882  0.75772676 -2.84928876  0.04696786]
 [-3.82703361  0.41831544 -1.230519    1.03108091]]
[[-3.85551279  0.51310473 -1.3713166   1.30221375]
 [-3.44916882  0.75772676 -2.84928876  0.04696786]
 [-3.82703361  0.41831544 -1.230519    1.03108091]]


In [12]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[-1.53674182 -0.39562836 -0.28992861]
 [ 0.36574425  1.56563487 -1.66618417]
 [ 0.59636057 -1.80179965 -0.49280365]]
[[-1.20192572]
 [ 2.13718422]
 [-2.15265158]]
[[ 1.84704952  0.47551589  0.34847265]
 [ 0.78166284  3.34605015 -3.56094252]
 [-1.28375653  3.87864686  1.06083456]]
