In [1]:
import numpy as np

In [2]:
x = np.arange(4)

In [3]:
x

array([0, 1, 2, 3])

In [4]:
xx = x.reshape(4,1)

In [5]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [6]:
y = np.ones(5)

In [7]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [8]:
z = np.ones((3,4))

In [9]:
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [10]:
x.shape

(4,)

In [11]:
y.shape

(5,)

In [12]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [13]:
xx.shape

(4, 1)

In [14]:
x + xx

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

### So, how did this happen? 

```
x = [0 1 2 3]
xx = [0
      1
      2
      3]
x  is         1 x 4
xx is         4 x 1
x op xx =>    4 x 4.
```

Basically we'll duplicate both to make them able to add to each other. Remember, np.arrays operations are element-wise.

```
    So,  x = [0 1 2 3       xx = [0 0 0 0
             0 1 2 3             1 1 1 1
             0 1 2 3             2 2 2 2 
             0 1 2 3]            3 3 3 3]
```

Now, just add them element wise. 

```
Hence, x + xx =  [0+0  1+0  2+0  3+0
                  0+1  1+1  2+1  3+1
                  0+2  1+2  2+2  3+2
                  0+3  1+3  2+3  3+3]  
                  
              = [0 1 2 3
                 1 2 3 4
                 2 3 4 5
                 3 4 5 6]
                 ```
                 

In [15]:
x * xx

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])