In [1]:
import numpy as np

So, we're gonna have a look at intuition behind understanding how numpy formats multidimensional data in np.arrays. 

In [2]:
3*4*5*6

360

In [4]:
simple1dArray = np.arange(3*4*5*6)
simple1dArray

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [5]:
simple4darray = simple1dArray.reshape(3,4,5,6)
simple4darray

array([[[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125],
         [126, 127, 128, 129, 130, 131],
         [132, 133, 134, 135, 136, 137],
         [138, 139, 140, 141, 142, 143],
      

Now, forget the output for a minute. Think of imaginging a 4D space. Well, you know how 3D space works, right? Just imagine an array of 3D spaces. Like, imagine parallel universes. 

Now, if you look at the above output, you'll see lots of 2D arrays at first. Like, one of them is : 

```
        [[330, 331, 332, 333, 334, 335],
         [336, 337, 338, 339, 340, 341],
         [342, 343, 344, 345, 346, 347],
         [348, 349, 350, 351, 352, 353],
         [354, 355, 356, 357, 358, 359]]
```

This is a `5 x 6` array. 
There are 3 groups above...and each group in that has 4 such 2D arrays. Which makes it of shape `3 x 4 x 5 x 6`

In [6]:
# Just [:-1] gives you all elements except the last one. Like, an array without element 359 in this case. [::-1] reverses array
another1dArray = np.arange(3*4*5*6)[::-1]
another1dArray

array([359, 358, 357, 356, 355, 354, 353, 352, 351, 350, 349, 348, 347,
       346, 345, 344, 343, 342, 341, 340, 339, 338, 337, 336, 335, 334,
       333, 332, 331, 330, 329, 328, 327, 326, 325, 324, 323, 322, 321,
       320, 319, 318, 317, 316, 315, 314, 313, 312, 311, 310, 309, 308,
       307, 306, 305, 304, 303, 302, 301, 300, 299, 298, 297, 296, 295,
       294, 293, 292, 291, 290, 289, 288, 287, 286, 285, 284, 283, 282,
       281, 280, 279, 278, 277, 276, 275, 274, 273, 272, 271, 270, 269,
       268, 267, 266, 265, 264, 263, 262, 261, 260, 259, 258, 257, 256,
       255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243,
       242, 241, 240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230,
       229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217,
       216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204,
       203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191,
       190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 17

In [8]:
another4dArray = another1dArray.reshape(6,5,4,3)
another4dArray

array([[[[359, 358, 357],
         [356, 355, 354],
         [353, 352, 351],
         [350, 349, 348]],

        [[347, 346, 345],
         [344, 343, 342],
         [341, 340, 339],
         [338, 337, 336]],

        [[335, 334, 333],
         [332, 331, 330],
         [329, 328, 327],
         [326, 325, 324]],

        [[323, 322, 321],
         [320, 319, 318],
         [317, 316, 315],
         [314, 313, 312]],

        [[311, 310, 309],
         [308, 307, 306],
         [305, 304, 303],
         [302, 301, 300]]],


       [[[299, 298, 297],
         [296, 295, 294],
         [293, 292, 291],
         [290, 289, 288]],

        [[287, 286, 285],
         [284, 283, 282],
         [281, 280, 279],
         [278, 277, 276]],

        [[275, 274, 273],
         [272, 271, 270],
         [269, 268, 267],
         [266, 265, 264]],

        [[263, 262, 261],
         [260, 259, 258],
         [257, 256, 255],
         [254, 253, 252]],

        [[251, 250, 249],
         [248, 247

Now, we can observe...there are 2d arrays of size `4 x 3`. An array of 5 such 2d arrays in each group. And a total of 6 such groups. 

### Dot Product

Now, for 1d arrays, dot product is nothing but multiplication. Let me give you an example

In [14]:
a = np.array([1,2,3])
b = np.array([5,6])
np.dot(a,b)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

**Obviously, it won't work because if you see these in 2D shapes, they're `1 x 3` and `1 x 2`**

In [15]:
a = np.array([1,2,3])
b = np.array([5])
np.dot(a,b)

ValueError: shapes (3,) and (1,) not aligned: 3 (dim 0) != 1 (dim 0)

**Similarly, here also. `1 x 3` and `1 x 1` won't fit together either**
`np.dot` basically does Matrix Multiplication, the way we've known it for 2d matrices (But, of course it can do it for N-d matrices also)


In [16]:
a = np.array([1,2,3])
b = np.array([[1],
    [2],
    [3]])

In [17]:
np.dot(a,b)

array([14])

That was easy, right? `1*1 + 2*2 + 3*3 = 14`

**Let's do it for 2d matrices also.**

In [18]:
p = np.array([1,2,3,4]).reshape(2,2)
p

array([[1, 2],
       [3, 4]])

In [20]:
# Intentially trying to screw up with reshape. :-)
q = np.array([5,6,7]).reshape(2,2)
q

ValueError: cannot reshape array of size 3 into shape (2,2)

In [21]:
q = np.array([5,6,7,8]).reshape(2,2)
q

array([[5, 6],
       [7, 8]])

In [24]:
np.dot(p,q)

array([[19, 22],
       [43, 50]])

Let's call this dot product matrix X. 

**`X[0,0] = p[0,0]*q[0,0] + p[0,1]*q[1,0] = 5 + 14 = 19.`**

So on...we can get other values also.

But, can we try to write another notation for X[0,0] ? 

Let's check.

In [34]:
# In a 1-D array
# a[i:j] => items from i through j-1
# p[:i] => items from beginning till i-1
# p[i:] => items from i till end

# In a 2-D array
# a[i:j,k:l]  => items from ith to j-1th row and columns matching k to l-1. 
# For example
twoDarray = np.arange(9).reshape(3,3)
twoDarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
twoDarray[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [36]:
twoDarray[:,0:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

You get the point. 

Now, let's rethink our problem again. Can we come up for a shorthand notation for X[0,0] ? 

**`X[0,0] = np.dot(p[0:1,:],q[:,0:1])`**

Will that work? 

In [37]:
p[0:1,:]

array([[1, 2]])

In [38]:
q[:,0:1]

array([[5],
       [7]])

In [39]:
np.dot(p[0:1,:],q[:,0:1])

array([[19]])

Awesome!

So, it works. Let's generalize it a bit further. 

**`X[i,j] = np.dot(p[i:i+1,:],q[:,j:j+1])`**

Is that correct? Let's check. 
We know X[0,1] = 22

In [40]:
np.dot(p[0:1,:],q[:,1:2])

array([[22]])

What about X[1,1] = 50? 

In [41]:
np.dot(p[1:2,:],q[:,1:2])

array([[50]])

Awesome. So, it works. The formula is correct. 

**`X[i,j] = np.dot(p[i:i+1,:], q[:,j:j+1])`**

Actually, `p[i:i+1,:]` can be written as `p[i,:]`, since we're only wanting ith row. 

So, the formula becomes

**`X[i,j] = np.dot(p[i,:], q[:,j])`**

Okay. We've come quite far. Just hold on a bit more. 

Now, let's see two results. 

In [42]:
np.dot(p[0,:],q[:,1])

22

In [43]:
sum(p[0,:] * q[:,1])

22

In [44]:
p[0,:] * q[:,1]

array([ 6, 16])

So, now we know 
**`np.dot(p[0,:],q[:,1])  =  sum(p[0,:],q[:,1])`**

Hence, new formula : 

**`X[i,j] = sum(p[0,:],q[:,1])`**

Now, let's look at the definition of np.dot for N-D arrays.
```
For N dimensions it is a sum product over the last axis of a and the second-to-last of b

dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
```

Just focus on the RHS of the equation. Last axis of the first array, and second-to-last of the second array.

Isn't that what we came at for our 2D array np.dot?

**`X[i,j] = sum(p[0,:],q[:,1])`**

For 2 dimensions, we're using 2nd axis of the first array and 1st axis of the second array. 

Now you get the intuition? We're just expanding the same thing to N-dimensions in case of N-dimensions formula.