In [2]:
import numpy as np

In [3]:
np.__version__

'1.12.0'

In [4]:
L = list(range(10))

In [5]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Matrices with numpy

In [6]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype='float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [8]:
np.full((3,5),1.23)

array([[ 1.23,  1.23,  1.23,  1.23,  1.23],
       [ 1.23,  1.23,  1.23,  1.23,  1.23],
       [ 1.23,  1.23,  1.23,  1.23,  1.23]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

**Create a matrix with mean 0 and standard deviation 1**

In [11]:
np.random.normal(0,1,(3,3))

array([[-0.39014323,  0.31780808, -1.20588879],
       [-0.49739535,  0.09097992,  0.10698384],
       [ 0.05725151, -0.05867402,  1.29243033]])

3d array/matrix/vector with random numbers

In [12]:
x1 = np.random.randint(10, size=(3,4,5))

In [13]:
x1

array([[[2, 4, 3, 8, 2],
        [7, 1, 7, 0, 9],
        [0, 6, 3, 4, 4],
        [7, 3, 7, 1, 8]],

       [[1, 7, 1, 5, 6],
        [0, 7, 4, 3, 9],
        [8, 5, 7, 8, 6],
        [0, 5, 5, 7, 3]],

       [[1, 7, 9, 0, 9],
        [4, 1, 9, 0, 1],
        [1, 0, 2, 6, 9],
        [8, 9, 8, 5, 5]]])

In [14]:
x1.ndim

3

In [15]:
x1.shape

(3, 4, 5)

In [16]:
x1.size

60

### Array Indexing

In [17]:
x2 = np.array([3,4,5,6,7])

In [18]:
x2

array([3, 4, 5, 6, 7])

In [19]:
x2[1]

4

In [20]:
x2[-1]

7

In [21]:
x3 = np.random.randint(10, size=(3,4))

In [22]:
x3

array([[9, 1, 7, 6],
       [7, 4, 4, 1],
       [4, 2, 8, 2]])

In [23]:
x3[0]

array([9, 1, 7, 6])

In [24]:
x3[0,2]

7

**Get first column**

In [25]:
x3[:,0]

array([9, 7, 4])

In [26]:
x3[0,0] = 10

In [27]:
x3

array([[10,  1,  7,  6],
       [ 7,  4,  4,  1],
       [ 4,  2,  8,  2]])

### Array Slicing
Access multiple or range of elements from an array

In [28]:
arr1 = np.arange(10)

In [29]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [31]:
arr1[5:]

array([5, 6, 7, 8, 9])

In [32]:
arr1[1::2]

array([1, 3, 5, 7, 9])

**nifty way to reverse an array**

In [33]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

*concatenation of arrays*

In [34]:
a = np.array([1,2,3])

In [35]:
b = np.array([4,5,6])

In [36]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

**Concatenation can convert 2x3 to 4x3**

See carefully that there is an extra square bracket below

In [37]:
grid = np.array([[1,1,1],[2,2,2]])

In [38]:
np.concatenate([grid,grid])

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

**Concatenation can convert 2x3 to 2*6**

In [39]:
np.concatenate([grid,grid],axis=1)

array([[1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2]])

***What if we wish to concatenate arrays of different dimensions?***

Then comes np.vstack and np.hstack to the rescue

In [40]:
a1 = np.array([3,4,5])

In [41]:
a2 = np.array([[1,2,3],[7,8,9]])

In [42]:
a1

array([3, 4, 5])

In [43]:
a2

array([[1, 2, 3],
       [7, 8, 9]])

In [44]:
np.vstack([a1,a2])

array([[3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [45]:
colArr = np.array([[9],[9]])

In [46]:
colArr

array([[9],
       [9]])

In [47]:
np.hstack([a2,colArr])

array([[1, 2, 3, 9],
       [7, 8, 9, 9]])

**Splitting array based on pre-defined positions**

In [48]:
parArr = np.arange(10)

In [49]:
parArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
child1,child2,child3 = np.split(parArr,[3,6])

In [51]:
print child1,child2,child3

[0 1 2] [3 4 5] [6 7 8 9]


**Re-shaping array to change dimensions**

In [53]:
grid = np.arange(16).reshape((4,4))

In [54]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
upper,lower = np.vsplit(grid,[2])

In [59]:
print upper, "\n\n", lower

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]


In [60]:
type(lower)

numpy.ndarray